export const surveyJsonKz = {
    showProgressBar: true,
    progressBarLocation: "top",
    pageNextText: "Далее",
    pagePrevText: "Назад",
    completeText: "Отправить",
    clearText: "exit",

    pages: [
        {
            // title: "count of pages",

            elements: [
                {
                    type: "dropdown",
                    name: "отдел",
                    title: "Бөлімді таңдаңыз",
                    isRequired: true,
                    showNoneItem: true,
                    showOtherItem: true,
                    placeholder: " Бөлім ",
                    choices: [
                        "КХО",
                        "ИК-1",
                        "ИК-2",
                        "Гинекология",
                        "Аритмология",
                        "Терапия 2 ",
                        "ОХ и ТХ",
                        "НХО",
                        "Урология",
                        "ДКХО",
                    ],
                },
                {
                    type: "radiogroup",
                    name: "пол",
                    title: "Жынысыңызды таңдаңыз",
                    isRequired: true,

                    colCount: 2,
                    choices: ["Мужской", "Женский"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "возраст",
                    title: "Сіздің жасыңыз",
                    isRequired: true,

                    colCount: 3,
                    choices: [
                        "меньше 15",
                        "от 16 - до 30",
                        "от 31 - до 40",
                        "от 41 - до 50",
                        "от 51 - до 60",
                        "больше 60",
                    ],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "panel",
                    name: "	Сіз қызмет көрсету жеделдігіне қаншалықты қанағаттанасыз: ",
                    elements: [
                        {
                            type: "rating",
                            name: "Регистратура",
                            title: "Тіркеу бөлімі",
                            isRequired: true,
                            autoGenerate: false,
                            rateCount: 10,
                            rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        },
                        {
                            type: "rating",
                            name: "Лечебный отдел",
                            title: "Емдеу бөлімі",
                            isRequired: true,
                            autoGenerate: false,
                            rateCount: 10,
                            rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        },
                        {
                            type: "rating",
                            name: "Приемный отдел",
                            title: "Қабылдау бөлімі",
                            isRequired: true,
                            autoGenerate: false,
                            rateCount: 10,
                            rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        },
                        {
                            type: "rating",
                            name: "Диагностический отдел",
                            title: "Диагностикалық бөлімі",
                            isRequired: true,
                            autoGenerate: false,
                            rateCount: 10,
                            rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                        },
                    ],

                    questionTitleLocation: "top",
                    // title: "Насколько Вы удовлетворены оперативностью обслуживания",
                },
            ],
        },
        {
            title: "Бөлімде сіз алып жатқан тексеру мен емдеудің сапасын бағалаңыз: ",
            elements: [
                {
                    type: "rating",
                    name: "Лечащего врача",
                    title: "Емдеуші дәрігердің",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Дежурного врача",
                    title: "Кезекші дәрігердің ",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Медицинской сестры",
                    title: "Медбикенің  ",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Младшего мед персонала",
                    title: "Кіші медициналық персоналдың",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Персонала диагностических отделов",
                    title: "Диагностикалық бөлім персоналының ",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Персонала реанимационных отделов",
                    title: "Реанимация бөлімі персоналының",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Персонала отдела восстановительного лечения",
                    title: "Қайта қалпына келтіріп емдеу бөлімі персоналының",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
            ],
        },
        {
            title: "Сіз бөлімдегі персоналдың сыпайылығы мен ілтипаттылығына қанағаттанасыз ба?",
            elements: [
                {
                    type: "rating",
                    name: "Удовлетворены ли Вы вежливостью и внимательностью Врача",
                    title: "Дәрігердің",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Удовлетворены ли Вы вежливостью и внимательностью Медсестры",
                    title: "Медбикелердің",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Насколько Вы удовлетворены полнотой информирования перед операцией, манипуляциями, процедурами",
                    title: "Сіз операциялардың, манипуляциялардың, рәсімдердің алдындағы ақпараттандырудың толықтылығына қаншалықты қанағаттанасыз:",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Оцените качество и полноту рекомендации врача при выписке",
                    title: "Дәрігердің емдеп шығару кезіндегі ұсыныстарының сапасы мен толықтылығын бағалаңыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Оцените качество питания",
                    title: "Тамақтандырудың сапасын бағалаңыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Оцените внешний вид персонала",
                    title: "Персоналдың сыртқы түрін бағалаңыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Оцените сервисные услуги (чистота палаты, киоск, парковка, охрана)",
                    title: "Сервистік қызметтерді бағалаңыз (палатаның тазалығы, шаштараз, киоск, дәріхана, көлік қою орны, күзет)",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
            ],
        },
        {
            elements: [
                {
                    type: "rating",
                    name: "Оцените , насколько Вы готовы рекомендовать нашу клинику",
                    title: "Біздің клиниканы ұсынуға қаншалықты дайын екеніңізді бағалаңыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Оцените , насколько Вы готовы рекомендовать нашу клинику вашим друзьям и знакомым",
                    title: "Сіз біздің клиниканы өзіңіздің достарыңыз бен таныстарыңызға ұсынуға қаншалықты дайын екендігіңізді бағалаңыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Оцените, насколько Вы предпочли бы повторно обратиться в нашу клинику при необходимости обследования и лечения",
                    title: "Сіз қажет болған жағдайда және тексеру мен емделу кезінде біздің клиникаға қайтадан келуге қаншалықты ниетті екеніңізді бағалаңыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Насколько Вы удовлетворены в целом клиникой?",
                    title: "Сіз жалпы клиникаға қаншалықты қанағаттанасыз?",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Как Вы оцениваете удобство ориентировки по указателям в учреждении",
                    title: "Мекемедегі нұсқау белгілері арқылы жол таба алуыңызды қалай бағалайсыз?",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Как Вы оцениваете своевременность выполнения медперсоналом назначеных процедур",
                    title: "Медициналық персоналдың тағайындалған процедураларды уақытылы орындауын қалай бағалайсыз?",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Как Вы оцениваете соблюдение правил безопасности для Вашего здоровья при проведении процедур",
                    title: "Процедуралар жүргізу кезінде денсаулығыңыз үшін қауіпсіздік ережелерінің сақталуын қалай бағалайсыз?",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                // {
                //     type: "rating",
                //     name: "Была ли предоставлена Вам возможность свободного выбора врача",
                //     title: "Была ли предоставлена Вам возможность свободного выбора врача",
                //     isRequired: true,
                //     autoGenerate: false,
                //     rateCount: 10,
                //     rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                // },
                {
                    type: "rating",
                    name: "Как Вы оцениваете наличие информационных / образовательных пособий для пациентов",
                    title: "Пациенттерге арналған ақпараттық / білім беру құралдарының бар-жоғын қалай бағалайсыз?",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
                {
                    type: "rating",
                    name: "Как Вы оцениваете качество лечения в стационаре",
                    title: "Ауруханада емдеу сапасын қалай бағалайсыз",
                    isRequired: true,
                    autoGenerate: false,
                    rateCount: 10,
                    rateValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                },
            ],
        },
        {
            elements: [
                {
                    type: "radiogroup",
                    name: "Была ли предоставлена Вам возможность свободного выбора врача",
                    title: "Сізге дәрігерді еркін таңдау мүмкіндігі берілді ме?",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Соблюдается ли конфиденциальность во время осмотра / процедура",
                    title: "Процедура/қаралу барысында құпиялықтың сақталуы қамтамасыз етіле ме?",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Было ли получено от Вас согласие перед исследованием или началом лечения ",
                    title: "Емдеуді бастамас бұрын сіздің келісіміңіз алынды ма?",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Мыл ли медицинский работник руки перед Вашим осмотром , манипуляцией , контактом ? ",
                    title: "Медициналық қызметкер сізді қарамас бұрын, манипуляция жасамас бұрын немесе байланысқа түспес бұрын қолын жуды ма?",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Приходилось ли Вам приобретать недостающие для лечения лекарственные препараты за счет собсвенных средств ( при лечении по квоте ) ",
                    title: "Ем алу кезінде, емдеуге қажетті дәрі-дәрмектердің жетіспеушілігіне байланысты оларды өз қаражатыңызға сатып алуға тура келді ме (квота бойынша)?",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Приходилось ли Вам осуществлять оплату медицинские услуги непосредственно медперсоналу, минуя кассу, если да (ФИО сотрудника)",
                    title: "Сізге медициналық қызметтер үшін ақшаны кассадан тыс, тікелей медицина қызметкеріне төлеуге тура келді ме? Егер иә болса - сонында толық фио жазыңыз",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Была ли предоставлена информация об альтернативных методах лечения?",
                    title: "Баламалы(альтернативті) емдеу туралы ақпарат берілді ме?",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Работала ли в палате кнопка вызова?",
                    title: "Палатада шақыру түймесі жұмыс істеді ме",
                    isRequired: true,

                    colCount: 3,
                    choices: ["Да", "Нет", "Затрудняюсь ответить"],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
            ],
        },
        {
            elements: [
                {
                    type: "radiogroup",
                    name: "Длительность ожидания в приемном покое при госпитализации (укажите какие)",
                    title: "Ауруханаға жатқызу кезінде қабылдау бөлімінде күту ұзақтығы (қайсысын көрсетіңіз)  ",
                    isRequired: true,

                    colCount: 3,
                    choices: [
                        "Меньше 15 мин",
                        "15-30 мин",
                        "30-45 мин",
                        "45 мин - 1 час",
                        "1 час и больше",
                    ],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    type: "radiogroup",
                    name: "Медицинское обслуживание в этом Центре (подчеркните нужное)",
                    title: " Осы орталықтағы медициналық көмек (қажеттісін атап көрсетіңіз)",
                    isRequired: true,

                    colCount: 1,
                    choices: [
                        "Лучше, чем в других медицинских организациях",
                        "Такое же, как и в других медицинских организациях",
                        "Хуже, чем в других медицинских организациях",
                        "Не знаю",
                    ],
                    separateSpecialChoices: true,
                    allowClear: true,
                },
                {
                    name: "Укажите Ваши замечания, пожелания, предложения по организации работы больницы и повышению качества оказания медицинской помощи:",
                    title: "Сіздің жалпы  клиника бойынша қызмет көрсету, диагностика және емдеу рәсімдерін жақсарту жөніндегі тілектеріңіз: ",
                    type: "comment",
                },
            ],
        },
    ],
};
